# Generated by Django 3.2.5 on 2022-04-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=550)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
