# Generated by Django 3.2.5 on 2022-04-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220423_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='s',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
