# Generated by Django 3.2.5 on 2022-04-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_upload_date_uploadfile_uploaddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
