# Generated by Django 3.2.5 on 2022-04-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_uploadfile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
