# Generated by Django 3.2.5 on 2022-04-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='url',
        ),
        migrations.AddField(
            model_name='upload',
            name='file',
            field=models.FileField(default=None, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
