# Generated by Django 3.2.5 on 2022-04-24 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_upload_s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadFile',
        ),
    ]
