# Generated by Django 3.2.5 on 2022-04-24 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_upload_uploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='upload_date',
            new_name='uploadDate',
        ),
    ]
