# Generated by Django 3.2.5 on 2022-04-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_uploadfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='description',
            field=models.TextField(blank=True, default=None),
        ),
    ]
